[programs.localnet]
usage = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
