[package]
name = "solana-gateway"
version = "0.3.0"
description = "OCIV Gateway Program"
authors = ["Daniel Kelleher <daniel@identity.com>"]
repository = "https://github.com/identity-com/on-chain-identity-gateway"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
# This must stay on 0.9.* as solana-program is using 0.9.1
borsh = "0.9.1"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.17"
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "=1.14.17"
solana-sdk = "=1.14.17"
tokio = { version = "1.0", features = ["macros"]}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
